spring.application.name=WorkOrderLocal

server.port=10000

central.url=http://localhost:10001

mock.qr-sim.enabled=true

# Workstation identity: {"machineName":"..."} written by admin UI; project root when cwd is server root
workstation.machine.config.file=./workstation-machine.json

